//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPS.Automation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AutomationConfigurationManagerResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AutomationConfigurationManagerResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPS.Automation.AutomationConfigurationManagerResource", typeof(AutomationConfigurationManagerResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppServerName.
        /// </summary>
        internal static string AppServerName_Key {
            get {
                return ResourceManager.GetString("AppServerName_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTOMATION_BROWSER.
        /// </summary>
        internal static string AUTOMATION_BROWSER_KEY {
            get {
                return ResourceManager.GetString("AUTOMATION_BROWSER_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTOMATION_TEST_ENVIRONMENT.
        /// </summary>
        internal static string AUTOMATION_TEST_ENVIRONMENT_KEY {
            get {
                return ResourceManager.GetString("AUTOMATION_TEST_ENVIRONMENT_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \MMSG.Automation\ApplicationDownloadedFiles.
        /// </summary>
        internal static string AutomationConfig_DownloadFile_Path {
            get {
                return ResourceManager.GetString("AutomationConfig_DownloadFile_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \..\..\..\MMSG.Pages.
        /// </summary>
        internal static string AutomationConfig_Testdata_Path {
            get {
                return ResourceManager.GetString("AutomationConfig_Testdata_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BatchProcess.
        /// </summary>
        internal static string BatchProcess_Path {
            get {
                return ResourceManager.GetString("BatchProcess_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to execBatchProcess.
        /// </summary>
        internal static string BatchProcessFile_Name {
            get {
                return ResourceManager.GetString("BatchProcessFile_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser.
        /// </summary>
        internal static string BrowserName_Key {
            get {
                return ResourceManager.GetString("BrowserName_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMET.
        /// </summary>
        internal static string Comet_ProductName {
            get {
                return ResourceManager.GetString("Comet_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ucSEM_PopupErrorMsg.
        /// </summary>
        internal static string COMET_ServerError {
            get {
                return ResourceManager.GetString("COMET_ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://{0}/Comet.
        /// </summary>
        internal static string COMET_URL {
            get {
                return ResourceManager.GetString("COMET_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMETDEVAPP01.
        /// </summary>
        internal static string COMETURLRootDEVAPP01_Key {
            get {
                return ResourceManager.GetString("COMETURLRootDEVAPP01_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMETDEVAPP05.
        /// </summary>
        internal static string COMETURLRootDEVAPP05_Key {
            get {
                return ResourceManager.GetString("COMETURLRootDEVAPP05_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMETDEVAPP16.
        /// </summary>
        internal static string COMETURLRootDEVAPP16_Key {
            get {
                return ResourceManager.GetString("COMETURLRootDEVAPP16_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://Environment.conavmaxxia.com.au.
        /// </summary>
        internal static string CONAV_URL {
            get {
                return ResourceManager.GetString("CONAV_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContinueExecutionAfterFailure.
        /// </summary>
        internal static string ContinueExecutionAfterFailure_Key {
            get {
                return ResourceManager.GetString("ContinueExecutionAfterFailure_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBCommandTimeoutInSeconds.
        /// </summary>
        internal static string DBCommandTimeout_Key {
            get {
                return ResourceManager.GetString("DBCommandTimeout_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source={0};Trusted_Connection=Yes;.
        /// </summary>
        internal static string DBConnectionString {
            get {
                return ResourceManager.GetString("DBConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBServerName.
        /// </summary>
        internal static string DBServerName_Key {
            get {
                return ResourceManager.GetString("DBServerName_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOWNLOAD_PATH.
        /// </summary>
        internal static string DOWNLOAD_PATH_Key {
            get {
                return ResourceManager.GetString("DOWNLOAD_PATH_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment.
        /// </summary>
        internal static string Environment_Key {
            get {
                return ResourceManager.GetString("Environment_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \MMSG.Automation\extent-config.xml.
        /// </summary>
        internal static string ExtentReportAppConfig_FileName {
            get {
                return ResourceManager.GetString("ExtentReportAppConfig_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to extent-config.
        /// </summary>
        internal static string ExtentReportAppConfigFileName {
            get {
                return ResourceManager.GetString("ExtentReportAppConfigFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\..\..\.
        /// </summary>
        internal static string Folder_TraversePath {
            get {
                return ResourceManager.GetString("Folder_TraversePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestData.
        /// </summary>
        internal static string InMemoryTestData_Path {
            get {
                return ResourceManager.GetString("InMemoryTestData_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string Log_Path {
            get {
                return ResourceManager.GetString("Log_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMSG.Automation.
        /// </summary>
        internal static string LogFile_Name {
            get {
                return ResourceManager.GetString("LogFile_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate/Verify.
        /// </summary>
        internal static string Login_Page_MOL_Activation {
            get {
                return ResourceManager.GetString("Login_Page_MOL_Activation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMSG_TESTDATA_PATH.
        /// </summary>
        internal static string MMSG_TESTDATA_PATH_Key {
            get {
                return ResourceManager.GetString("MMSG_TESTDATA_PATH_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://{0}-{1}.outsystemsenterprise.com/SecureMaxxia/login.aspx.
        /// </summary>
        internal static string MOL_URL {
            get {
                return ResourceManager.GetString("MOL_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOLDEVAPP01.
        /// </summary>
        internal static string MOLURLRootDEVAPP01_Key {
            get {
                return ResourceManager.GetString("MOLURLRootDEVAPP01_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOLDEVAPP05.
        /// </summary>
        internal static string MOLURLRootDEVAPP05_Key {
            get {
                return ResourceManager.GetString("MOLURLRootDEVAPP05_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOLDEVAPP16.
        /// </summary>
        internal static string MOLURLRootDEVAPP16_Key {
            get {
                return ResourceManager.GetString("MOLURLRootDEVAPP16_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Out\.
        /// </summary>
        internal static string Output_Path {
            get {
                return ResourceManager.GetString("Output_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string Product_Key {
            get {
                return ResourceManager.GetString("Product_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string Reports_Path {
            get {
                return ResourceManager.GetString("Reports_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://{0}.secureremserv.com.au.
        /// </summary>
        internal static string ROL_URL {
            get {
                return ResourceManager.GetString("ROL_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROLDEVAPP01.
        /// </summary>
        internal static string ROLURLRootDEVAPP01_Key {
            get {
                return ResourceManager.GetString("ROLURLRootDEVAPP01_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROLDEVAPP05.
        /// </summary>
        internal static string ROLURLRootDEVAPP05_Key {
            get {
                return ResourceManager.GetString("ROLURLRootDEVAPP05_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROLDEVAPP16.
        /// </summary>
        internal static string ROLURLRootDEVAPP16_Key {
            get {
                return ResourceManager.GetString("ROLURLRootDEVAPP16_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScreenShots.
        /// </summary>
        internal static string ScreenShots_Path {
            get {
                return ResourceManager.GetString("ScreenShots_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPCommandTimeoutInSeconds.
        /// </summary>
        internal static string SPCommandTimeout_Key {
            get {
                return ResourceManager.GetString("SPCommandTimeout_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestData.
        /// </summary>
        internal static string TestData_Path {
            get {
                return ResourceManager.GetString("TestData_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _TestReport_.
        /// </summary>
        internal static string Testreport_Name {
            get {
                return ResourceManager.GetString("Testreport_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \..\..\..\TestResults\.
        /// </summary>
        internal static string Testresult_Path {
            get {
                return ResourceManager.GetString("Testresult_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestTimeOut.
        /// </summary>
        internal static string TestTimeOut_Key {
            get {
                return ResourceManager.GetString("TestTimeOut_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _.
        /// </summary>
        internal static string TextSeparator {
            get {
                return ResourceManager.GetString("TextSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://mslmcotfs01:8080/tfs/McMillan%20Shakespeare%20Australia/MMSG/_apis/test/runs/{0}/attachments?api-version=3.2-preview.1.
        /// </summary>
        internal static string TFS_API_AttachFile_Endpoint {
            get {
                return ResourceManager.GetString("TFS_API_AttachFile_Endpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://mslmcotfs01:8080/tfs/McMillan%20Shakespeare%20Australia/MMSG/_apis/test/runs/.
        /// </summary>
        internal static string TFS_API_GetAllTestRuns_Endpoint {
            get {
                return ResourceManager.GetString("TFS_API_GetAllTestRuns_Endpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \..\.
        /// </summary>
        internal static string TraversePath {
            get {
                return ResourceManager.GetString("TraversePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML.
        /// </summary>
        internal static string XMLFolderName {
            get {
                return ResourceManager.GetString("XMLFolderName", resourceCulture);
            }
        }
    }
}
